### PR TITLE
[#23] Configurable Discovery Mode

### LINKED ISSUE #23: Configurable Discovery Mode
As time has proven the original approach of the `SpringCloudCommandRouter`, thus using `ServiceInstance` metadata to communicate command handling capabilities, no longer suffices for a multitude of Spring Cloud Discovery mechanism implementations. This follows from the fact that as far as we know currently no implementation allows continued updates on this metadata in a live set up.

That leaves the `SpringCloudHttpBackupCommandRouter` as the sole reasonable solution, with a rather awkward naming attached to it. As it's no longer a back-up, but the _only_ solution.
We feel an overhaul on the `SpringCloudCommandRouter` is thus in place. 

Instead of the current set up we should introduce the capability to configure a (for a lack of better word) `DiscoveryMode` on the `SpringCloudCommandRouter`.

This `DiscoveryMode` would provide the implementation on how to receive and send command routing information from one instance to another. We think the following implementations would be reasonable to introduce:

- Dynamic-HTTP -> Essentially the current implementation of the `SpringCloudHttpBackupCommandRouter`. This should be the default.
- Simple / AcceptAll -> In a "homogeneous command handling"-system, each node can handle everything. Thus there is no real need to share this knowledge at all. Kuddos to @dhermanns in #22 for sharing this idea.

### PR DESCRIPTION
**Pull request by smcvb**
This pull request provides a `CapabilityDiscoveryMode`, in doing so resolving issue #23.
The `CapabilityDiscoveryMode` is in charge of maintaining and sharing the local instance's capabilities, as well as discovering what the remote instances can do. This information will be stored in a `MemberCapabilities` object, which has a default (`DefaultMemberCapabilities)` and serializable (`SerializedMemberCapabilities`) implementation.

Furthermore, the main implementation of the `CapabilityDiscoveryMode` is the `RestCapabilityDiscoveryMode`. Essentially this will take the role of the `SpringCloudHttpBackupCommandRouter`, allowing this implementation to be deprecated. Additionally a `SimpleCapabilityDiscoveryMode` is added for homogeneous setups, solving #22. 
Lastly, a wrapper implementation is provided which can mark certain `ServiceInstance`s as to be ignored (which is called the `IgnoreListingCapabilityDiscoveryMode`). This behaviour was hardcoded in the `SpringCloudCommandRouter`, but can now be disabled if desired.

This new `CapabilityDiscoveryMode` is used by the `SpringCloudCommandRouter`. It simplifies the `SpringCloudCommandRouter`, and as stated earlier deprecates the `SpringCloudHttpBackupCommandRouter` entirely. In a similar fashion has the `MessageRoutingInformation` been deprecated, as it did not suit the current needs _and_ as it was only used by the `SpringCloudHttpBackupCommandRouter` internally.

The last points of interest are (firstly) the fact JUnit 5 has been introduced. At this stage there's a mixture of JUnit4 and JUnit 5, not to over encumber this pull request further. Secondly, the sole thing which has been removed in favour of simplicity, as the cleaning of the ignored `ServiceInstance` list. The `SpringCloudCommandRouter` used to do this for _any_ instances no longer discoverable from the `DiscoveryClient`. As the `CapabilityDiscoveryMode` however deals with single instances instead of a list, this capability can no longer be performed by the `IgnoreListingCapabilityDiscoveryMode` in its previous form. Added, any solutions in that area will essentially lead to a "re-evaluation approach" of ignored `ServiceInstance`s, which should be covered in issue #6.

This pull request resolves #23.

### CODE REVIEW

**Review by YvonneCeelie — APPROVED** [review]
Looks good!

**Comment by CatalinCaprita** [comment]
Hi, I get the following error on using the RestCapabilityDiscoveryMode:  404 : [{"timestamp":"2021-02-08T10:24:11.303+00:00","status":404,"error":"Not Found","message":"","path":"/member-capabilities%7D"}].

**Comment by smcvb** [comment]
I guess the culprit lies in the `%7D` you note at the end of the `/member-capabilities%7D` endpoint. 
`%7D` stands for `}` I believe, which would suggest that somewhere the bracket is leaking through.

Would you mind trying to set the `memberCapabilitiesEndpoint` to `/member-capabilities` on the `RestCapabilityDiscoveryMode`?
It should be redundant, but if you are changing the `axon.distributed.spring-cloud.rest-mode-url` property and you are creating the `RestCapabilityDiscoveryMode` yourself (as shared), then you need to make sure both are the same.

> Additionally, it appears that spring boot does not recognize the specifiec new properties for the .yml file :
> Cannot resolve configuration property 'axon.distributed.spring-cloud.rest-mode-url'.

Uncertain why this is the case to be honest. I've seen it act flakily myself sometimes, but if I recall correctly there shouldn't be anything we need to do other than marking the class which will collect the properties in your `.properties`/`.yml` file with `@ConfigurationProperties`.
At any note, I'd regard that as a separate issue. Let us know whether defining the `memberCapabilitiesEndpoint` (through the builder) does the trick.

**Comment by CatalinCaprita** [comment]
Hello, Steven
Thank you for replying at such short notice!
After having done some deep diving into the updated .md document as well as inspecting the every SpringCloudAutoConfiguration class, as well as considering your suggestion:
> Would you mind trying to set the memberCapabilitiesEndpoint to /member-capabilities on the RestCapabilityDiscoveryMode?
It should be redundant, but if you are changing the axon.distributed.spring-cloud.rest-mode-url property and you are creating the RestCapabilityDiscoveryMode yourself (as shared), then you need to make sure both are the same.

It seems that the problem was I was not declaring a rest-mode-url at all in the ``.yml`` file, but declaring a ``memberCapabilitiesEndpoint`` (different than the defaul ``/member-capabilities`` through the ``@Configuration`` class. So, if declaring a custom endpoint through a custom configuration class, there is a need to set the same ``rest-mode-url`` inside the ``.yml`` file as well.

**Comment by smcvb** [comment]
Gotcha. I am assuming adjusting the behaviour accordingly has solved the problem you were having then, correct?

**Comment by CatalinCaprita** [comment]
Indeed, it did! My apologies for the late response. Although to me it appears rather counterintuitive that not specifying the ``rest-mode-url`` in a ``.yml`` / ``.properties`` implies assuming the default value _even after__ specifically customizing the endpoint in code.

**Comment by smcvb** [comment]
Agreed. A nicer solution might be an option. 
Then again, we/I mainly assumed users to utilize the Spring Boot Auto Configuration with a properties/yml file.
Thus, a user would never be required to mainly construct a `RestCapabilityDiscoveryMode`.

Granted, you have a point worth of improving. 
This would specifically require an adjustment in the `MemberCapabilitiesController` which in that case is unable to use the class-level `@RequestMapping` annotation is it currently is defined.

Thanks for bringing this to light @CatalinCaprita, and of course happy to hear the problem has been resolved. :-)

**Pull request merged**
